-- MySQL Script generated by MySQL Workbench
-- dom 27 dic 2020 14:05:31 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `chatui_participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatui_participante` (
  `id_participante` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `avatar` VARCHAR(255) NULL,
  `date_add` VARCHAR(45) NULL,
  PRIMARY KEY (`id_participante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatui_etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatui_etiqueta` (
  `id_etiqueta` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `date_add` DATETIME NULL,
  PRIMARY KEY (`id_etiqueta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatui_conversacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatui_conversacion` (
  `id_conversacion` INT NOT NULL,
  `date_add` DATETIME NULL,
  `date_upd` DATETIME NULL,
  PRIMARY KEY (`id_conversacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatui_mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatui_mensajes` (
  `id_mensaje` INT NOT NULL,
  `chatui_conversacion_id_conversacion` INT NOT NULL,
  `from` INT NULL,
  `to` INT NULL,
  `mensaje` TEXT NULL,
  `date_add` DATETIME NULL,
  PRIMARY KEY (`id_mensaje`, `chatui_conversacion_id_conversacion`),
  INDEX `fk_chatui_mensajes_chatui_conversacion1_idx` (`chatui_conversacion_id_conversacion` ASC),
  INDEX `fk_chatui_mensajes_from_idx` (`from` ASC),
  INDEX `fk_chatui_mensajes_to_idx` (`to` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatui_conversacion_has_chatui_participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatui_conversacion_has_chatui_participante` (
  `chatui_conversacion_id_conversacion` INT NOT NULL,
  `chatui_participante_id_participante` INT NOT NULL,
  PRIMARY KEY (`chatui_conversacion_id_conversacion`, `chatui_participante_id_participante`),
  INDEX `fk_chatui_conversacion_has_chatui_participante_chatui_parti_idx` (`chatui_participante_id_participante` ASC),
  INDEX `fk_chatui_conversacion_has_chatui_participante_chatui_conve_idx` (`chatui_conversacion_id_conversacion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatui_conversacion_has_chatui_etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatui_conversacion_has_chatui_etiqueta` (
  `chatui_conversacion_id_conversacion` INT NOT NULL,
  `chatui_etiqueta_id_etiqueta` INT NOT NULL,
  PRIMARY KEY (`chatui_conversacion_id_conversacion`, `chatui_etiqueta_id_etiqueta`),
  INDEX `fk_chatui_conversacion_has_chatui_etiqueta_chatui_etiqueta1_idx` (`chatui_etiqueta_id_etiqueta` ASC),
  INDEX `fk_chatui_conversacion_has_chatui_etiqueta_chatui_conversac_idx` (`chatui_conversacion_id_conversacion` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
